name: camera_extended_ios
description: iOS implementation of camera_extended plugin with native aspect ratio support (16:9, 4:3, 1:1).
repository: https://github.com/erykkruk/camera_extensions
issue_tracker: https://github.com/erykkruk/camera_extensions/issues
version: 0.9.24

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: camera_extended
    platforms:
      ios:
        pluginClass: CameraPlugin
        dartPluginClass: AVFoundationCamera

dependencies:
  camera_extended_platform_interface: ^2.12.2
  flutter:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any
  mockito: ^5.4.4
  pigeon: ^26.1.0

topics:
  - camera
