name: camera_extended_ios_example
description: Demonstrates how to use the camera_extended_ios plugin.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  camera_extended_ios:
    # When depending on this package from a real application you should use:
    #   camera_extended_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  camera_extended_platform_interface:
    path: ../../camera_platform_interface
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  video_player: ^2.7.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
